### ISSUE TITLE
Compilation failure when trying to convert a field value to a reference

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#2456]
Attempting to put a unit field into a references in the following example produces a compilation failure when I would have expected it to work:

```ruby
# foo.spicy
module Consumer; # works for me if named `foo`.

public type Bar = unit {
    a: Outer;
};

type Outer = unit {
    a: Foo &convert=new Foo($$);
};

type Foo = unit {};
```

```console
$ spicyc -dj foo.spicy -o foo.hlto

=== Uh oh ... C++ compilation failed ===

This is unexpected and should not happen. Please help us fix the issue
by opening a ticket at https://github.com/zeek/spicy/issues/new.

Please include the content of the following file with your report:

  "/private/tmp/repro/hilti-jit-error.log"

That file contains diagnostics from the C++ compiler. Please also
include your Spicy code that triggered this error, ideally reduced to
a small snippet still exhibiting the issue if you can.

===

[error] spicyc: JIT compilation failed
make: *** [foo.hlto] Error 1
```

```
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
HILTI version 1.16.1

## [job 3] ccache clang++ -c -I/opt/homebrew/Cellar/zeek/8.2.1/include -fPIC -std=c++20 -g -O0 -fvisibility=hidden -Wno-invalid-offsetof -I/opt/homebrew/Cellar/zeek/8.2.1/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk -Wall -Wno-unused -funsigned-char -Wno-c2y-extensions -Wno-register -Werror=vla -funsigned-char -Wno-c2y-extensions -o /var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/Consumer_1a8c9128dba77178-410b2ecd5a942a10.cc_1a8c9128dba77178.o /private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/Consumer_1a8c9128dba77178-410b2ecd5a942a10.cc

/private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/Consumer_1a8c9128dba77178-410b2ecd5a942a10.cc:149:5: error: use of undeclared identifier 'Foo'
  149 |     Foo::Foo() {
      |     ^
1 error generated.
```

That changing naming changes behavior reads suspicious to me. This first broke for me with 370254bf89720377e050c50fc0d5bac0cfdd588c which appeared with spicy-1.12.0.

This came from @mohandhawan.

**Comment by mdhawan** [comment]
The code compiles for me now with this fix. Thanks @bbannier .
