### ISSUE TITLE
Failed to compile using GCC 11.2.1

### ISSUE THREAD

**Issue by AmazingPP** [zeek/spicy#1891]
The document states that only GCC >= 9 is required.

https://github.com/zeek/spicy/blob/ab69192894caef32e7bca316ec6fa5e65d4a40a4/doc/installation.rst#L210

Error log:
```bash
/spicy/spicy/runtime/src/base64.cc: In member function ‘hilti::rt::Bytes spicy::rt::base64::Stream::encode(const hilti::rt::Bytes&)’:
/spicy/spicy/runtime/src/base64.cc:38:40: error: call of overloaded ‘basic_string(SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, <brace-enclosed initializer list>)’ is ambiguous
   38 |     std::string buf(data.size() * 2, {});
      |                                        ^
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:55,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/stdexcept:39,
                 from /spicy/hilti/runtime/include/hilti/rt/types/bytes.h:7,
                 from /spicy/spicy/runtime/src/base64.cc:3:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3734:9: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
 3734 |         basic_string(_InputIterator __beg, _InputIterator __end,
      |         ^~~~~~~~~~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3673:7: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
 3673 |       basic_string(size_type __n, _CharT __c, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
/spicy/spicy/runtime/src/base64.cc: In member function ‘hilti::rt::Bytes spicy::rt::base64::Stream::decode(const hilti::rt::Bytes&)’:
/spicy/spicy/runtime/src/base64.cc:63:40: error: call of overloaded ‘basic_string(SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, <brace-enclosed initializer list>)’ is ambiguous
   63 |     std::string buf(data.size() * 2, {});
      |                                        ^
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:55,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/stdexcept:39,
                 from /spicy/hilti/runtime/include/hilti/rt/types/bytes.h:7,
                 from /spicy/spicy/runtime/src/base64.cc:3:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3734:9: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
 3734 |         basic_string(_InputIterator __beg, _InputIterator __end,
      |         ^~~~~~~~~~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3673:7: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
 3673 |       basic_string(size_type __n, _CharT __c, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
```

**Comment by bbannier** [comment]
I cannot reproduce this so some more details would be helpful. I checked the current development head ab69192894caef32e7bca316ec6fa5e65d4a40a4 against different versions of GCC. For that I modified an [existing Debian-based setup](https://github.com/zeek/spicy/blob/ab69192894caef32e7bca316ec6fa5e65d4a40a4/docker/Dockerfile.debian-12) to use [`gcc`](https://github.com/zeek/spicy/blob/ab69192894caef32e7bca316ec6fa5e65d4a40a4/docker/Dockerfile.debian-12) instead of the Debian images (the GCC Docker images are Debian-based),

```patch
-FROM debian:bookworm-slim
+FROM gcc:9
```

This built fine for e.g., gcc-9.5 or gcc-11.2.0 (I could not find a gcc-11.2.1 release).

What did you do to see this error?

**Comment by evantypanski** [comment]
Does this happen to be on Windows or targeting Windows in some way? The suspicious part is `SafeInt<uint64_t>` converting into some standard size type there - GCC uses [LLP64](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) in mingw, so that'd trigger the weirdness of 32 bit longs on Windows.

If this is using mingw, that's probably the problem. I think that'd be unsupported if it's true

**Comment by AmazingPP** [comment]
I am using devtoolset-11-gcc on CentOS 7.

```bash
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-11/root/usr --mandir=/opt/rh/devtoolset-11/root/usr/share/man --infodir=/opt/rh/devtoolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)
```

**Comment by bbannier** [comment]
Did you try whether above patch by @evantypanski helps in any way?

Otherwise could you share a `Dockerfile` which reproduces how you set up your system, and how you configure and build Spicy? We had a setup for building on centos-7 (with `detoolset-9` at the time), but [dropped support for it](https://github.com/zeek/spicy/commit/55d7775de25c8558082e21dc40c6b0be2f7477a2) when centos-7 reached its end of life. Trying to resurrect that fails since mirrors went away.

IIRC devtoolset at least by default would inject a compiler, but e.g., still link against a system `libstdc++` (so that binaries with `devtoolset` resolve when run in the host env). Not sure that could be the issue here.

**Comment by AmazingPP** [comment]
> Did you try whether above patch by @evantypanski helps in any way?

I tried the patch, and it works perfectly.

> Otherwise could you share a `Dockerfile` which reproduces how you set up your system, and how you configure and build Spicy? 

No problem.

```Dockerfile
FROM centos:7

RUN sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/*.repo

RUN yum -y install \
    epel-release \
    centos-release-scl \
  && yum clean all && rm -rf /var/cache/yum

RUN sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/^# baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/CentOS-SCLo-scl*.repo

RUN yum -y install \
    bison \
    flex \
    cmake3 \
    make \
    which \
    git \
    zlib-devel \
    devtoolset-11 \
  && yum clean all && rm -rf /var/cache/yum
```

Then use the `source /opt/rh/devtoolset-11/enable` command to enable GCC 11 in bash.
