### ISSUE TITLE
Generated code for widening integer assignment in a field hook produces redefinition of '_t_dd'

### ISSUE THREAD

**Issue by stevesmoot** [zeek/spicy#2404]
/tmp/vex/vex.spicy:
  module vex;

  public type Msg = unit {
      var wide: uint32;
      narrow: uint16 { self.wide = $$; }   # uint16 -> uint32 widening in a field hook
  };

  spicyc -j vex.spicy

  .../vex_*.cc:226:41: warning: parentheses were disambiguated as redundant
     parentheses around declaration of variable named '_t_dd' [-Wvexing-parse]
    226 |     ::hilti::rt::integer::safe<uint32_t>(_t_dd);
  .../vex_*.cc:226:42: error: redefinition of '_t_dd' with a different type:
     '::hilti::rt::integer::safe<uint32_t>' vs 'const ::hilti::rt::integer::safe<uint16_t> &'

Spicy:     v1.16.0 (version-number 11600), release build
           (bundled with Homebrew zeek 8.2.0, prefix /opt/homebrew/Cellar/zeek/8.2.0)
Spicy built with C++ compiler:  clang++
JIT C++ compiler (at runtime):  Apple clang 21.0.0 (clang-2100.1.1.101)
OS:        macOS 26.5 (build 25F71), Darwin 25.5.0, arm64

[hilti-jit-error.log](https://github.com/user-attachments/files/28900577/hilti-jit-error.log)

**Comment by bbannier** [comment]
Thank you for the report! FTR, this regressed with https://github.com/zeek/spicy/pull/2249 which was first released with spicy-1.16.0.
