### ISSUE TITLE
Cannot initialize unit with inout parameter

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy#1266]
The following code raises a compilation error:

```
module Test;

public type Message = unit {
	sink testsink;

	on %init {
		self.testsink.connect(new La(self));
	}
};

public type La = unit(inout msg: Message) {
};
```

Output:
```
$ spicyz test.spicy -o test.hlto
In file included from /private/var/folders/xg/y2l9jptj6bq6gm7rz1mm2lc80000gn/T/Test_192a3a6f2a106f95-4d51f94efa94032b.cc:6:
In file included from /Users/johanna/zeek/install/include/hilti/rt/libhilti.h:11:
In file included from /Users/johanna/zeek/install/include/hilti/rt/context.h:12:
In file included from /Users/johanna/zeek/install/include/hilti/rt/fiber.h:19:
/Users/johanna/zeek/install/include/hilti/rt/types/reference.h:703:31: error: no matching conversion for functional-style cast from '__hlt::Test::Message' to '__hlt::Test::La'
    return StrongReference<T>(T(std::forward<Args>(args)...));
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/xg/y2l9jptj6bq6gm7rz1mm2lc80000gn/T/Test_192a3a6f2a106f95-4d51f94efa94032b.cc:317:59: note: in instantiation of function template specialization 'hilti::rt::reference::make_strong<__hlt::Test::La, __hlt::Test::Message &>' requested here
    (*(*__self).testsink).connect(::hilti::rt::reference::make_strong<__hlt::Test::La>((*__self)));
                                                          ^
/private/var/folders/xg/y2l9jptj6bq6gm7rz1mm2lc80000gn/T/Test_192a3a6f2a106f95-4d51f94efa94032b.cc:58:9: note: candidate constructor not viable: no known conversion from '__hlt::Test::Message' to 'const __hlt::Test::La' for 1st argument
        La(const La&) = default;
        ^
/private/var/folders/xg/y2l9jptj6bq6gm7rz1mm2lc80000gn/T/Test_192a3a6f2a106f95-4d51f94efa94032b.cc:59:9: note: candidate constructor not viable: no known conversion from '__hlt::Test::Message' to '__hlt::Test::La' for 1st argument
        La(La&&) = default;
        ^
/private/var/folders/xg/y2l9jptj6bq6gm7rz1mm2lc80000gn/T/Test_192a3a6f2a106f95-4d51f94efa94032b.cc:111:16: note: candidate constructor not viable: no known conversion from '__hlt::Test::Message' to '::hilti::rt::ValueReference<__hlt::Test::Message> &' for 1st argument
    inline La::La(::hilti::rt::ValueReference<__hlt::Test::Message>& __p_msg) : __p_msg(std::move(__p_msg)) {
               ^
/private/var/folders/xg/y2l9jptj6bq6gm7rz1mm2lc80000gn/T/Test_192a3a6f2a106f95-4d51f94efa94032b.cc:108:16: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    inline La::La() {
               ^
1 error generated.
[error] <Spicy Plugin for Zeek>: JIT compilation failed
```

I did not test this too thoroughtly - but it also seems to happen when trying to pass things different from `self`.

This is happening with spicy zeek/spicy@10b17c8b2829a47f4a6d7f16454befa56dc396e7 bundled with zeek zeek/zeek@e580a8b3568e68b1598ee5eccb08ca8fa270ff9b.

**Comment by bbannier** [comment]
Marking this as regression since @0xxon mentioned that this worked in March 2021.

**Comment by bbannier** [comment]
This was broken by 29054778950981cda2a5adbae3d66cae953cc795 which first appeared with v1.4.0.

**Comment by rsmmr** [comment]
I have a fix for this, but just for the record: `La(*self)` isn't expected to work, `self` shouldn't be dereferenceable (and with the fix, this will indeed now abort with an error).
