### ISSUE TITLE
Referencing `public` `const` from other modules triggers C++ compiler error

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#1079]
We can reference a `global` from another module if it is declared `public`. The docs suggest that a `const` should behave similarly, but this leads to a C++ compiler error.

```.ruby
# a.spicy
module a;

public global x: uint32 = 64;
public const y: uint32 = 64;
```

```.ruby
# b.spicy
module b;

import a;
print(a::x); # Works on its own.
print(a::y); # Fails during C++ compile.
```

```.console
$ spicyc -j b.spicy
/private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/hilti-rt-test-IUGmp0/b.cc:29:25: error: no member named 'y' in namespace '__hlt::a'; did you mean simply 'y'?
    ::hilti::rt::print((__hlt::a::y), ::hilti::rt::Bool(true));
                        ^~~~~~~~~~~
                        y
/private/var/folders/ht/vtb0rkbd4ws15vx02xdb84zw0000gn/T/hilti-rt-test-IUGmp0/b.cc:20:48: note: 'y' declared here
    const ::hilti::rt::integer::safe<uint32_t> y = ::hilti::rt::integer::safe<std::uint32_t>{64u};
                                               ^
1 error generated.
[error] spicyc: JIT compilation failed
```

I would have expected a `const` to behave identical to a `global` here.
