### PR TITLE
Fix GCC 11 compilation failure.

### LINKED ISSUE #1891: Failed to compile using GCC 11.2.1
The document states that only GCC >= 9 is required.

https://github.com/zeek/spicy/blob/ab69192894caef32e7bca316ec6fa5e65d4a40a4/doc/installation.rst#L210

Error log:
```bash
/spicy/spicy/runtime/src/base64.cc: In member function ‘hilti::rt::Bytes spicy::rt::base64::Stream::encode(const hilti::rt::Bytes&)’:
/spicy/spicy/runtime/src/base64.cc:38:40: error: call of overloaded ‘basic_string(SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, <brace-enclosed initializer list>)’ is ambiguous
   38 |     std::string buf(data.size() * 2, {});
      |                                        ^
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:55,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/stdexcept:39,
                 from /spicy/hilti/runtime/include/hilti/rt/types/bytes.h:7,
                 from /spicy/spicy/runtime/src/base64.cc:3:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3734:9: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
 3734 |         basic_string(_InputIterator __beg, _InputIterator __end,
      |         ^~~~~~~~~~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3673:7: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
 3673 |       basic_string(size_type __n, _CharT __c, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
/spicy/spicy/runtime/src/base64.cc: In member function ‘hilti::rt::Bytes spicy::rt::base64::Stream::decode(const hilti::rt::Bytes&)’:
/spicy/spicy/runtime/src/base64.cc:63:40: error: call of overloaded ‘basic_string(SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>, <brace-enclosed initializer list>)’ is ambiguous
   63 |     std::string buf(data.size() * 2, {});
      |                                        ^
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:55,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/stdexcept:39,
                 from /spicy/hilti/runtime/include/hilti/rt/types/bytes.h:7,
                 from /spicy/spicy/runtime/src/base64.cc:3:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3734:9: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = SafeInt<long unsigned int, hilti::rt::integer::detail::SafeIntException>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
 3734 |         basic_string(_InputIterator __beg, _InputIterator __end,
      |         ^~~~~~~~~~~~
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3673:7: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
 3673 |       basic_string(size_type __n, _CharT __c, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by evantypanski**
Fixes #1891

I still haven't reproduced the issue, but this seems to fix it. Honestly, I don't even know what really caused it. It's just probably good to use an explicit cast to get the overload we want rather than relying on user defined conversions.

### CODE REVIEW

File: spicy/runtime/src/base64.cc [hunk 1]
```diff
@@ -35,7 +35,7 @@ hilti::rt::Bytes Stream::encode(const hilti::rt::Bytes& data) {
     if ( ! _state )
         throw Base64Error("encoding already finished");
 
-    std::string buf(data.size() * 2, {});
+    std::string buf(static_cast<std::size_t>(data.size() * 2), {});
     auto len = base64_encode_block(data.data(), static_cast<int>(data.size()), buf.data(), &_state->estate);
```
Comment (bbannier) [inline spicy/runtime/src/base64.cc:39]: Not changed by you, but could you add a patch here so we cast to the correct target type for `length_in`?

```suggestion
    auto len = base64_encode_block(data.data(), static_cast<size_t>(data.size()), buf.data(), &_state->estate);
```

There should be three additional instances of this.

**Review by bbannier — COMMENTED** [review]
> I still haven't reproduced the issue, but this seems to fix it. Honestly, I don't even know what really caused it. It's just probably good to use an explicit cast to get the overload we want rather than relying on user defined conversions.

Yeah, this is a weird one. We set `hilti::rt::Bytes::size_type` (type of `data.size()`) to a `integer::safe<uint64_t>` which could at least break this code semantically at runtime if `std::string::size_type` is smaller. I am not sure how to set up such a configuration.

Avoiding the reliance on implicit conversions is great, we'd still want to make sure that casts do not silently truncate values at runtime. I just checked that a `static_cast` on an `hilti::rt::integer::safe` checks for that, and it does.

**Comment by bbannier** [comment]
And congrats on PR #1900!

File: spicy/runtime/src/base64.cc [hunk 2]
```diff
@@ -35,7 +35,7 @@ hilti::rt::Bytes Stream::encode(const hilti::rt::Bytes& data) {
     if ( ! _state )
         throw Base64Error("encoding already finished");
 
-    std::string buf(data.size() * 2, {});
+    std::string buf(static_cast<std::size_t>(data.size() * 2), {});
```
[the remark this answers is not in the document]
Comment (evantypanski) [reply spicy/runtime/src/base64.cc]: Honestly I thought they would always be the same thing, but apparently it's technically possible they aren't. Hmph.
