### ISSUE TITLE
Vector of enum cannot be constructed like other vectors

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy#361]
The following code currently fails in JIT with d4a3823,
```
module Foo;

type S = unit {};
type E = enum { A, B, C };

function works1(): vector<uint8> { return vector<uint8>(); }
function works2(): vector<uint8> { return vector<uint8>(); }
function works4(): vector<S> { return vector<S>(); }
function works5(): vector<S> { return []; }

function broken1(): vector<E> { return []; }
function broken2(): vector<E> { return vector<E>(); }
```

```
$ spicyc foo.spicy -j
Foo.cc:122:12: error: no viable conversion from returned value of type 'Vector<Foo::E, (default) std::__1::allocator<__hlt::Foo::E>>' to function return type 'Vector<Foo::E, hilti::rt::vector::Allocator<Foo::E, Foo::E::Undef>>'
    return hilti::rt::Vector<Foo::E>({});
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:183:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'const hilti::rt::Vector<__hlt::Foo::E, hilti::rt::v
ector::Allocator<__hlt::Foo::E, __hlt::Foo::E::Undef> > &' for 1st argument
    Vector(const Vector& other) : V(other) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:184:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'hilti::rt::Vector<__hlt::Foo::E, hilti::rt::vector:
:Allocator<__hlt::Foo::E, __hlt::Foo::E::Undef> > &&' for 1st argument
    Vector(Vector&& other) noexcept : V(std::move(other)) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:186:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'std::initializer_list<E>' for 1st argument
    Vector(std::initializer_list<T> init, const Allocator& alloc = Allocator()) : V(std::move(init), alloc) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:188:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'const rt::List<E> &' for 1st argument
    Vector(const rt::List<T>& l) : std::vector<T>(l.begin(), l.end()) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:189:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'rt::List<E> &&' for 1st argument
    Vector(rt::List<T>&& l) : std::vector<T>(std::move_iterator(l.begin()), std::move_iterator(l.end())) {}
    ^
Foo.cc:127:12: error: no viable conversion from returned value of type 'Vector<Foo::E, (default) std::__1::allocator<__hlt::Foo::E>>' to function return type 'Vector<Foo::E, hilti::rt::vector::Allocator<Foo::E, Foo::E::Undef>>'
    return hilti::rt::Vector<Foo::E>({});
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:183:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'const hilti::rt::Vector<__hlt::Foo::E, hilti::rt::v
ector::Allocator<__hlt::Foo::E, __hlt::Foo::E::Undef> > &' for 1st argument
    Vector(const Vector& other) : V(other) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:184:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'hilti::rt::Vector<__hlt::Foo::E, hilti::rt::vector:
:Allocator<__hlt::Foo::E, __hlt::Foo::E::Undef> > &&' for 1st argument
    Vector(Vector&& other) noexcept : V(std::move(other)) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:186:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'std::initializer_list<E>' for 1st argument
    Vector(std::initializer_list<T> init, const Allocator& alloc = Allocator()) : V(std::move(init), alloc) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:188:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'const rt::List<E> &' for 1st argument
    Vector(const rt::List<T>& l) : std::vector<T>(l.begin(), l.end()) {}
    ^
/usr/local/Cellar/spicy/HEAD-d4a3823/include/hilti/rt/types/vector.h:189:5: note: candidate constructor not viable: no known conversion from 'hilti::rt::Vector<Foo::E>' (aka 'Vector<__hlt::Foo::E>') to 'rt::List<E> &&' for 1st argument
    Vector(rt::List<T>&& l) : std::vector<T>(std::move_iterator(l.begin()), std::move_iterator(l.end())) {}
    ^
2 errors generated.
[error] jit: failed to execute compilation action.
[error] jit: failed to compile C++ code unit Foo to bitcode
[error] spicyc: JIT compilation failed
```

We probably are missing some handling for enum types when constructing vectors.
